version : '3'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
    - 5672:5672
    - 15672:15672

  order-creation-service:
    container_name: order-creation-service
    build: ./OrderCreationService
    ports:
      - 18080:8080
    depends_on:
      - rabbitmq
    environment:
      RABBIT_HOST: rabbitmq

  order-logging-service:
    container_name: order-logging-service
    build: ./OrderLoggingService
    depends_on:
      - rabbitmq
      - order-creation-service
    environment:
      RABBIT_HOST: rabbitmq

  start_dependencies:
    image: ubuntu:14.04
    depends_on:
    - order-creation-service
    command: >
      /bin/bash -c "
        while ! nc -z order-creation-service 8080;
        do
          echo sleeping;
          sleep 1;
        done;
        echo Connected!;
      "